<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CmD1yhMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CmD1yhM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CmD1yhM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'estimationoffrelivre' => ['privates', '.errored..service_locator.CmD1yhM.App\\Entity\\Estimationoffrelivre', NULL, 'Cannot autowire service ".service_locator.CmD1yhM": it references class "App\\Entity\\Estimationoffrelivre" but no such service exists.'],
        ], [
            'estimationoffrelivre' => 'App\\Entity\\Estimationoffrelivre',
        ]);
    }
}
