<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V1llBC1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v1llBC1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v1llBC1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clotureAchat' => ['privates', '.errored..service_locator.v1llBC1.App\\Entity\\ClotureAchat', NULL, 'Cannot autowire service ".service_locator.v1llBC1": it references class "App\\Entity\\ClotureAchat" but no such service exists.'],
        ], [
            'clotureAchat' => 'App\\Entity\\ClotureAchat',
        ]);
    }
}
