<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L0ZdMmSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L0ZdMmS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L0ZdMmS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'user' => ['privates', '.errored..service_locator.L0ZdMmS.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.L0ZdMmS": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'mailer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
