<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kckoz2rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kckoz2r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kckoz2r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detailslivraison' => ['privates', '.errored..service_locator.Kckoz2r.App\\Entity\\Detailslivraison', NULL, 'Cannot autowire service ".service_locator.Kckoz2r": it references class "App\\Entity\\Detailslivraison" but no such service exists.'],
        ], [
            'detailslivraison' => 'App\\Entity\\Detailslivraison',
        ]);
    }
}
