<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DHRj1hmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DHRj1hm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DHRj1hm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'estimationoffrelivre' => ['privates', '.errored..service_locator.DHRj1hm.App\\Entity\\Estimationoffrelivre', NULL, 'Cannot autowire service ".service_locator.DHRj1hm": it references class "App\\Entity\\Estimationoffrelivre" but no such service exists.'],
            'estimationoffrelivreRepository' => ['privates', 'App\\Repository\\EstimationoffrelivreRepository', 'getEstimationoffrelivreRepositoryService', true],
        ], [
            'estimationoffrelivre' => 'App\\Entity\\Estimationoffrelivre',
            'estimationoffrelivreRepository' => 'App\\Repository\\EstimationoffrelivreRepository',
        ]);
    }
}
