<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ccTGQJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ccTGQJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ccTGQJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'estimationoffrelivreRepository' => ['privates', 'App\\Repository\\EstimationoffrelivreRepository', 'getEstimationoffrelivreRepositoryService', true],
        ], [
            'estimationoffrelivreRepository' => 'App\\Repository\\EstimationoffrelivreRepository',
        ]);
    }
}
