<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClotureAchatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4NS_LPz.App\Entity\ClotureAchat' shared service.
     *
     * @return \App\Entity\ClotureAchat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.4NS_LPz": it references class "App\\Entity\\ClotureAchat" but no such service exists.');
    }
}
