<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetailslivraison3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jrJpXKw.App\Entity\Detailslivraison' shared service.
     *
     * @return \App\Entity\Detailslivraison
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jrJpXKw": it references class "App\\Entity\\Detailslivraison" but no such service exists.');
    }
}
