<?php

namespace Container9yvJtlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTopic2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UjK2YmA.App\Entity\Topic' shared service.
     *
     * @return \App\Entity\Topic
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UjK2YmA": it references class "App\\Entity\\Topic" but no such service exists.');
    }
}
