<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Topic extends \App\Entity\Topic implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'idtopic', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'titretopic', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'accepter', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'nbsujet', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'hide', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'iduser'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'idtopic', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'titretopic', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'accepter', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'nbsujet', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'hide', '' . "\0" . 'App\\Entity\\Topic' . "\0" . 'iduser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Topic $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdtopic(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdtopic();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtopic', []);

        return parent::getIdtopic();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitretopic(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitretopic', []);

        return parent::getTitretopic();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitretopic(?string $titretopic): \App\Entity\Topic
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitretopic', [$titretopic]);

        return parent::setTitretopic($titretopic);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Topic
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(?\DateTimeInterface $date): \App\Entity\Topic
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccepter(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccepter', []);

        return parent::isAccepter();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccepter(bool $accepter): \App\Entity\Topic
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccepter', [$accepter]);

        return parent::setAccepter($accepter);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbsujet(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbsujet', []);

        return parent::getNbsujet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbsujet(int $nbsujet): \App\Entity\Topic
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbsujet', [$nbsujet]);

        return parent::setNbsujet($nbsujet);
    }

    /**
     * {@inheritDoc}
     */
    public function getHide(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHide', []);

        return parent::getHide();
    }

    /**
     * {@inheritDoc}
     */
    public function setHide(int $hide): \App\Entity\Topic
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHide', [$hide]);

        return parent::setHide($hide);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduser', []);

        return parent::getIduser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduser(?\App\Entity\User $iduser): \App\Entity\Topic
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduser', [$iduser]);

        return parent::setIduser($iduser);
    }

}
