<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PnJ3gAtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PnJ3gAt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PnJ3gAt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'maileer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'sujet' => ['privates', '.errored..service_locator.PnJ3gAt.App\\Entity\\Sujet', NULL, 'Cannot autowire service ".service_locator.PnJ3gAt": it references class "App\\Entity\\Sujet" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'maileer' => '?',
            'sujet' => 'App\\Entity\\Sujet',
        ]);
    }
}
