<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nm7i4WUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nm7i4WU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nm7i4WU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'estimationoffrelivreRepository' => ['privates', 'App\\Repository\\EstimationoffrelivreRepository', 'getEstimationoffrelivreRepositoryService', true],
            'propositionlivre' => ['privates', '.errored..service_locator.nm7i4WU.App\\Entity\\Propositionlivre', NULL, 'Cannot autowire service ".service_locator.nm7i4WU": it references class "App\\Entity\\Propositionlivre" but no such service exists.'],
        ], [
            'estimationoffrelivreRepository' => 'App\\Repository\\EstimationoffrelivreRepository',
            'propositionlivre' => 'App\\Entity\\Propositionlivre',
        ]);
    }
}
