<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LEttiBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LEttiB_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LEttiB_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'propositionlivre' => ['privates', '.errored..service_locator.LEttiB_.App\\Entity\\Propositionlivre', NULL, 'Cannot autowire service ".service_locator.LEttiB_": it references class "App\\Entity\\Propositionlivre" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'propositionlivre' => 'App\\Entity\\Propositionlivre',
        ]);
    }
}
