<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JrJpXKwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jrJpXKw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jrJpXKw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detailslivraison' => ['privates', '.errored..service_locator.jrJpXKw.App\\Entity\\Detailslivraison', NULL, 'Cannot autowire service ".service_locator.jrJpXKw": it references class "App\\Entity\\Detailslivraison" but no such service exists.'],
            'detailslivraisonRepository' => ['privates', 'App\\Repository\\DetailslivraisonRepository', 'getDetailslivraisonRepositoryService', true],
        ], [
            'detailslivraison' => 'App\\Entity\\Detailslivraison',
            'detailslivraisonRepository' => 'App\\Repository\\DetailslivraisonRepository',
        ]);
    }
}
