<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BHa4f4LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BHa4f4L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BHa4f4L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clotureAchatRepository' => ['privates', 'App\\Repository\\ClotureAchatRepository', 'getClotureAchatRepositoryService', true],
            'iddetailslivraison' => ['privates', '.errored..service_locator.BHa4f4L.App\\Entity\\Detailslivraison', NULL, 'Cannot autowire service ".service_locator.BHa4f4L": it references class "App\\Entity\\Detailslivraison" but no such service exists.'],
        ], [
            'clotureAchatRepository' => 'App\\Repository\\ClotureAchatRepository',
            'iddetailslivraison' => 'App\\Entity\\Detailslivraison',
        ]);
    }
}
