<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XKciiGCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xKciiGC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xKciiGC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detailslivraisonRepository' => ['privates', 'App\\Repository\\DetailslivraisonRepository', 'getDetailslivraisonRepositoryService', true],
            'estimationoffrelivre' => ['privates', '.errored..service_locator.xKciiGC.App\\Entity\\Estimationoffrelivre', NULL, 'Cannot autowire service ".service_locator.xKciiGC": it references class "App\\Entity\\Estimationoffrelivre" but no such service exists.'],
            'estimationoffrelivreRepository' => ['privates', 'App\\Repository\\EstimationoffrelivreRepository', 'getEstimationoffrelivreRepositoryService', true],
        ], [
            'detailslivraisonRepository' => 'App\\Repository\\DetailslivraisonRepository',
            'estimationoffrelivre' => 'App\\Entity\\Estimationoffrelivre',
            'estimationoffrelivreRepository' => 'App\\Repository\\EstimationoffrelivreRepository',
        ]);
    }
}
