<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGZjSpwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QGZjSpw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QGZjSpw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'topic' => ['privates', '.errored..service_locator.QGZjSpw.App\\Entity\\Topic', NULL, 'Cannot autowire service ".service_locator.QGZjSpw": it references class "App\\Entity\\Topic" but no such service exists.'],
        ], [
            'topic' => 'App\\Entity\\Topic',
        ]);
    }
}
