<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4NSLPzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4NS_LPz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4NS_LPz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clotureAchat' => ['privates', '.errored..service_locator.4NS_LPz.App\\Entity\\ClotureAchat', NULL, 'Cannot autowire service ".service_locator.4NS_LPz": it references class "App\\Entity\\ClotureAchat" but no such service exists.'],
            'clotureAchatRepository' => ['privates', 'App\\Repository\\ClotureAchatRepository', 'getClotureAchatRepositoryService', true],
        ], [
            'clotureAchat' => 'App\\Entity\\ClotureAchat',
            'clotureAchatRepository' => 'App\\Repository\\ClotureAchatRepository',
        ]);
    }
}
