<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UjK2YmAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UjK2YmA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UjK2YmA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'topic' => ['privates', '.errored..service_locator.UjK2YmA.App\\Entity\\Topic', NULL, 'Cannot autowire service ".service_locator.UjK2YmA": it references class "App\\Entity\\Topic" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'topic' => 'App\\Entity\\Topic',
        ]);
    }
}
