<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEstimationoffrelivreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CmD1yhM.App\Entity\Estimationoffrelivre' shared service.
     *
     * @return \App\Entity\Estimationoffrelivre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CmD1yhM": it references class "App\\Entity\\Estimationoffrelivre" but no such service exists.');
    }
}
