<?php

namespace Container7NxTq3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropositionlivreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LEttiB_.App\Entity\Propositionlivre' shared service.
     *
     * @return \App\Entity\Propositionlivre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LEttiB_": it references class "App\\Entity\\Propositionlivre" but no such service exists.');
    }
}
