<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFRVQUk4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFRVQUk4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFRVQUk4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFRVQUk4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFRVQUk4\App_KernelDevDebugContainer([
    'container.build_hash' => 'FRVQUk4',
    'container.build_id' => 'c4e89b40',
    'container.build_time' => 1683387666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFRVQUk4');
