<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7NxTq3N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7NxTq3N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7NxTq3N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7NxTq3N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7NxTq3N\App_KernelDevDebugContainer([
    'container.build_hash' => '7NxTq3N',
    'container.build_id' => 'dd649b03',
    'container.build_time' => 1683017096,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7NxTq3N');
