<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9VaazVx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9VaazVx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9VaazVx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9VaazVx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9VaazVx\App_KernelDevDebugContainer([
    'container.build_hash' => '9VaazVx',
    'container.build_id' => '67a4defb',
    'container.build_time' => 1683029824,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9VaazVx');
